import { Container } from '@/components/layout/Container'
import { TransactionTable } from '@/components/transactions/TransactionTable'
import { Transaction } from '@/types'

// Mock data - will be replaced with Supabase in PROMPT 10
const mockTransactions: Transaction[] = [
  {
    id: '1',
    description: 'Conta de água',
    amount: 100,
    type: 'expense',
    category: 'Manutenção',
    date: '2026-01-17',
    account: 'Conta corrente',
    installments: '-',
  },
  {
    id: '2',
    description: 'Conta de Luz',
    amount: 150,
    type: 'expense',
    category: 'Manutenção',
    date: '2026-01-17',
    account: 'Conta corrente',
    installments: '-',
  },
  {
    id: '3',
    description: 'Passeio no parque',
    amount: 750,
    type: 'expense',
    category: 'Lazer',
    date: '2026-01-17',
    card: 'Cartão XP',
    installments: '1/1',
  },
  {
    id: '4',
    description: 'Salário',
    amount: 5000,
    type: 'income',
    category: 'Salário',
    date: '2026-01-15',
    account: 'Conta corrente',
    installments: '-',
  },
  {
    id: '5',
    description: 'Freelance',
    amount: 2000,
    type: 'income',
    category: 'Trabalho',
    date: '2026-01-14',
    account: 'Conta corrente',
    installments: '-',
  },
  {
    id: '6',
    description: 'Supermercado',
    amount: 350,
    type: 'expense',
    category: 'Alimentação',
    date: '2026-01-13',
    card: 'Cartão XP',
    installments: '-',
  },
  {
    id: '7',
    description: 'Farmácia',
    amount: 120,
    type: 'expense',
    category: 'Saúde',
    date: '2026-01-12',
    card: 'Cartão XP',
    installments: '-',
  },
  {
    id: '8',
    description: 'Uber',
    amount: 45,
    type: 'expense',
    category: 'Transporte',
    date: '2026-01-11',
    card: 'Cartão XP',
    installments: '-',
  },
  {
    id: '9',
    description: 'Netflix',
    amount: 45,
    type: 'expense',
    category: 'Entretenimento',
    date: '2026-01-10',
    card: 'Cartão XP',
    installments: '-',
  },
  {
    id: '10',
    description: 'Aluguel',
    amount: 1500,
    type: 'expense',
    category: 'Aluguel',
    date: '2026-01-05',
    account: 'Conta corrente',
    installments: '-',
  },
  {
    id: '11',
    description: 'Restaurante',
    amount: 180,
    type: 'expense',
    category: 'Alimentação',
    date: '2026-01-04',
    card: 'Cartão XP',
    installments: '-',
  },
  {
    id: '12',
    description: 'Gasolina',
    amount: 200,
    type: 'expense',
    category: 'Transporte',
    date: '2026-01-03',
    card: 'Cartão XP',
    installments: '-',
  },
  {
    id: '13',
    description: 'Academia',
    amount: 120,
    type: 'expense',
    category: 'Academia',
    date: '2026-01-02',
    card: 'Cartão XP',
    installments: '-',
  },
  {
    id: '14',
    description: 'Presente',
    amount: 250,
    type: 'expense',
    category: 'Outros',
    date: '2026-01-01',
    card: 'Cartão XP',
    installments: '-',
  },
  {
    id: '15',
    description: 'Venda produto',
    amount: 800,
    type: 'income',
    category: 'Vendas',
    date: '2025-12-30',
    account: 'Conta corrente',
    installments: '-',
  },
  {
    id: '16',
    description: 'Cinema',
    amount: 50,
    type: 'expense',
    category: 'Lazer',
    date: '2025-12-28',
    card: 'Cartão XP',
    installments: '-',
  },
  {
    id: '17',
    description: 'Consultório',
    amount: 300,
    type: 'expense',
    category: 'Saúde',
    date: '2025-12-25',
    card: 'Cartão XP',
    installments: '-',
  },
]

export function Transactions() {
  return (
    <Container>
      <TransactionTable transactions={mockTransactions} />
    </Container>
  )
}
